In [108]:
# exponential time complexity
def fibonacci1(n):
    if n <= 1:
        return 1   
    return fibonacci(n - 1) + fibonacci(n - 2)


def fibonacci(n, intermediate_dict={}):
    #print(intermediate_dict)
    if n <= 1:
        return 1 #n if start with zero
    if n not in intermediate_dict:
        intermediate_dict[n] = fibonacci(n-1, intermediate_dict) + fibonacci(n-2,intermediate_dict)
    return intermediate_dict[n]

no_of_elements = 50
# generally fibonacci number start with 0 1 1 2, but in questions it start with 1 1 2  
print("Fibonacci series:")
for i in range(no_of_elements):
    print("Element",i+1,"--------------",fibonacci(i))

Fibonacci series:
Element 1 -------------- 1
Element 2 -------------- 1
Element 3 -------------- 2
Element 4 -------------- 3
Element 5 -------------- 5
Element 6 -------------- 8
Element 7 -------------- 13
Element 8 -------------- 21
Element 9 -------------- 34
Element 10 -------------- 55
Element 11 -------------- 89
Element 12 -------------- 144
Element 13 -------------- 233
Element 14 -------------- 377
Element 15 -------------- 610
Element 16 -------------- 987
Element 17 -------------- 1597
Element 18 -------------- 2584
Element 19 -------------- 4181
Element 20 -------------- 6765
Element 21 -------------- 10946
Element 22 -------------- 17711
Element 23 -------------- 28657
Element 24 -------------- 46368
Element 25 -------------- 75025
Element 26 -------------- 121393
Element 27 -------------- 196418
Element 28 -------------- 317811
Element 29 -------------- 514229
Element 30 -------------- 832040
Element 31 -------------- 1346269
Element 32 -------------- 2178309
Element 33 -------------- 3524578
Element 34 -------------- 5702887
Element 35 -------------- 9227465
Element 36 -------------- 14930352
Element 37 -------------- 24157817
Element 38 -------------- 39088169
Element 39 -------------- 63245986
Element 40 -------------- 102334155
Element 41 -------------- 165580141
Element 42 -------------- 267914296
Element 43 -------------- 433494437
Element 44 -------------- 701408733
Element 45 -------------- 1134903170
Element 46 -------------- 1836311903
Element 47 -------------- 2971215073
Element 48 -------------- 4807526976
Element 49 -------------- 7778742049
Element 50 -------------- 12586269025

In [94]:
def fibonacci(n):
    #print(intermediate_results)
    if n <= 1:
        return 1   
    return fibonacci(n - 1) + fibonacci(n - 2)

no_of_element = 50
# generally fibonacci number start with 0 1 1 2, but in questions it start with 1 1 2  
print("Fibonacci series:")
for i in range(no_of_element):
    print("Element",i+1,"--------------",fibonacci(i))

Fibonacci series:
Element 1 -------------- 1
Element 2 -------------- 1
Element 3 -------------- 2
Element 4 -------------- 3
Element 5 -------------- 5
Element 6 -------------- 8
Element 7 -------------- 13
Element 8 -------------- 21
Element 9 -------------- 34
Element 10 -------------- 55
Element 11 -------------- 89
Element 12 -------------- 144
Element 13 -------------- 233
Element 14 -------------- 377
Element 15 -------------- 610
Element 16 -------------- 987
Element 17 -------------- 1597
Element 18 -------------- 2584
Element 19 -------------- 4181
Element 20 -------------- 6765
Element 21 -------------- 10946
Element 22 -------------- 17711
Element 23 -------------- 28657
Element 24 -------------- 46368
Element 25 -------------- 75025
Element 26 -------------- 121393
Element 27 -------------- 196418
Element 28 -------------- 317811
Element 29 -------------- 514229
Element 30 -------------- 832040
Element 31 -------------- 1346269
Element 32 -------------- 2178309
Element 33 -------------- 3524578
Element 34 -------------- 5702887
Element 35 -------------- 9227465
Element 36 -------------- 14930352
Element 37 -------------- 24157817
Element 38 -------------- 39088169
Element 39 -------------- 63245986

KeyboardInterrupt:

In [105]:
import random
#insertion sort
def ascending_order(list1):
    size = len(list1)
    for i in range(1, size): 
        key = list1[i]
        j = i-1
        while j >= 0 and key < list1[j] :
                list1[j+1] = list1[j]
                j = j - 1
        list1[j+1] = key        
    return list1

random.seed(0)
no_of_element=50
numbers = [random.randint(1,no_of_element) for i in range(no_of_element)]
print("Unsorted number:",numbers)

sorted_numbers = ascending_order(numbers)
print("Sorted numbers in ascending order:", sorted_numbers)

Unsorted number: [25, 49, 27, 3, 17, 33, 32, 26, 20, 31, 23, 38, 14, 33, 9, 19, 9, 49, 7, 40, 17, 35, 46, 39, 10, 20, 7, 47, 5, 44, 22, 31, 36, 7, 23, 28, 21, 40, 41, 14, 36, 31, 29, 34, 17, 4, 36, 1, 6, 47]
Sorted numbers in ascending order: [1, 3, 4, 5, 6, 7, 7, 7, 9, 9, 10, 14, 14, 17, 17, 17, 19, 20, 20, 21, 22, 23, 23, 25, 26, 27, 28, 29, 31, 31, 31, 32, 33, 33, 34, 35, 36, 36, 36, 38, 39, 40, 40, 41, 44, 46, 47, 47, 49, 49]

In [99]:
!ls

AI_DATA_POLICY_Assignment_1.pdf ascending_order.py
Untitled.ipynb                  fibonacci.py

In [91]:
import pandas as pd
df = pd.read_csv('asu.tsv',sep = '\t')
df

        RAJ2000    DEJ2000   SpT
0     80.622083  33.514028    O5
1    341.725458  58.084306  O5.5
2     32.260333  57.932194  O6.5
3     81.900625  34.755278    O7
4     96.159792  19.704389  O7.5
..          ...        ...   ...
156    1.514125  63.679667    O6
157  308.093417  41.305278    O7
158   32.932958  60.712361    B1
159  102.892125   0.297333    B1
160   49.718458  52.030056    B5

[161 rows x 3 columns]